### PR TITLE
add newsletter feed

### PR DESCRIPTION
**Pull request by maneesha**
Adds script to get newsletter feed from Mailchimp

### CODE REVIEW

**Comment by maneesha** [comment]
See also https://github.com/carpentries/carpentries.org/pull/445

**Comment by fmichonneau** [comment]
That looks good!

Have you already uploaded the API key on Travis?

We'll also need to add a rule in the Makefile:

```make
newsletter:
     ./bin/newsletter_feed.sh _data
```

and add this at the top on the file under `everything` like the other ones.

**Comment by maneesha** [comment]
Yes, the API key is in travis.

Just added changes to the Makefile.

**Comment by fmichonneau** [comment]
the last piece for this side is to add a `chmod +x bin/newsletter_feed.sh` to make the script executable on Travis.

**Comment by fmichonneau** [comment]
great, thanks Maneesha!

**Pull request merged**
